### PR TITLE
Custom fonts: fix title being cut off. Resolves #1936

### LINKED ISSUE #1936: Dialog's title being cut off when using custom font
**Library Version:**

3.1.1
 
**Affected Device(s):**
 
- Xiaomi Mi A2 lite with Android 9.0
- Nexus 5 with Android 8.1 (custom rom)
 
**Describe the Bug:**

I'm applying a custom font (lato in the example) to the dialog's title and the descender appears to be cut off.

**Edit**: the issue can't be reproduced with all custom fonts (raleway black works great for example).

**To Reproduce:**

Apply a custom font like lato to dialog's title

Senza nome

### PR DESCRIPTION
**Pull request by enricocid**

### CODE REVIEW

File: core/src/main/java/com/afollestad/materialdialogs/utils/MDUtil.kt [hunk 1]
```diff
@@ -234,6 +234,13 @@ object MDUtil {
     }
   }
 
+  @RestrictTo(LIBRARY_GROUP) fun TextView?.maybeSetAdditionalPadding(height: Int): Int {
```
Comment (afollestad) [inline core/src/main/java/com/afollestad/materialdialogs/utils/MDUtil.kt]: The receiver `TextView` doesn't need to be nullable here, since it's only used in `DialogTitleLayout` and the text view there is never null 😁

File: core/src/main/java/com/afollestad/materialdialogs/utils/MDUtil.kt [hunk 2]
```diff
@@ -234,6 +234,13 @@ object MDUtil {
...
+    if (this == null) return 0
+    val fm = paint.fontMetrics
+    val measuredHeight = fm.descent - fm.ascent
```
Comment (afollestad) [inline core/src/main/java/com/afollestad/materialdialogs/utils/MDUtil.kt]: It might be better to call `measuredHeight` here `textHeight` or something, since `measuredHeight` is used in many other places in the context of the view itself

File: core/src/main/java/com/afollestad/materialdialogs/internal/main/DialogTitleLayout.kt [hunk 3]
```diff
@@ -113,7 +114,7 @@ class DialogTitleLayout(
 
     val titleHalfHeight = titleView.measuredHeight / 2
     val titleTop = contentMidPoint - titleHalfHeight
-    val titleBottom = contentMidPoint + titleHalfHeight
+    val titleBottom = contentMidPoint + titleHalfHeight + titleView.maybeSetAdditionalPadding(titleView.measuredHeight)
```
Comment (afollestad) [inline core/src/main/java/com/afollestad/materialdialogs/internal/main/DialogTitleLayout.kt]: Can you wrap the third component here onto the next line?

**Comment by enricocid** [comment]
I'm not sure I'm able to update the PR XD. I'm very bad at GIT :)

**Comment by afollestad** [comment]
You just have to commit and push to your fork :)

**Comment by enricocid** [comment]
> You just have to commit and push to your fork :)

Sorry, still have extreme memories related to the gerrit/git madness X'D
Hope it is ok now :)

File: core/src/main/java/com/afollestad/materialdialogs/internal/main/DialogTitleLayout.kt [hunk 4]
```diff
@@ -114,6 +115,7 @@ class DialogTitleLayout(
     val titleHalfHeight = titleView.measuredHeight / 2
     val titleTop = contentMidPoint - titleHalfHeight
     val titleBottom = contentMidPoint + titleHalfHeight
+    + titleView.maybeSetAdditionalPadding(titleView.measuredHeight)
```
Comment (afollestad) [inline core/src/main/java/com/afollestad/materialdialogs/internal/main/DialogTitleLayout.kt]: Looks like `+ titleView.maybeSetAdditionalPadding(titleView.measuredHeight)` actually doesn't get used when it's formatted like this, but I'll fix it in a separate commit :) 

Should be

```kotlin
val titleBottom = contentMidPoint + titleHalfHeight +
        titleView.maybeSetAdditionalPadding(titleView.measuredHeight)
```

**Comment by Johnett** [comment]
Great work guys @afollestad and @enricocid.
